### ISSUE TITLE
The app is crashing

### ISSUE THREAD

**Issue by KL-Codman** [skal3mar/Spotify-Premium-apk#22]
The app crashes suddenly after 10 seconds of using.It closes itself.Ive tried resarting the app,clearing cache,force stop,reinstalling,restarting the phone and but no use.It was working fine yesterday but crashing since today morning
![Screenshot_20240719_081238_Device care](https://github.com/user-attachments/assets/69fd29b6-94e8-4a3d-b65d-3e496b7297b6)

**Comment by kezker** [comment]
while waiting on update/fix, I will be using previous release. It doesn't crash. You can try the same

**Comment by skal3mar** [comment]
i will add a new version today. for now, i recommend deleting the app's cache and data in the settings. it could help.

**Comment by skal3mar** [comment]
it should work fine, i will upload the latest version today
