### ISSUE TITLE
System crashing 

### ISSUE THREAD

**Issue by Learninh** [skal3mar/Spotify-Premium-apk#26]
A14 custom rom after logging into account system crashing

https://github.com/user-attachments/assets/1188fac2-97a0-40fb-abe6-a8ecfc98aadc

Tried reinstalling clearing cashe storage nothing worked 
Edit: i checked with original applicoation same problem it means this app itself has problem not this project

**Comment by Dineshgranger** [comment]
Use the previous version for now , the admin said he's inthe process of creating a new one

**Comment by skal3mar** [comment]
try using different rom for now
