### ISSUE TITLE
This version is not compatible for android 13, 14 

### ISSUE THREAD

**Issue by jerry7994111** [skal3mar/Spotify-Premium-apk#4]
i have samsung 21 ultra and android 14 i download your file and try to install but showing installation error. Then i go to spotiwire.com aur download latest [spotify premium mod apk](https://spotiwire.com/spotify-premium-apk/) and install to enjoy latest music.

**Comment by jameswwe** [comment]
Oh, I see what you mean! Looks like there's a bit of trouble with the version you mentioned for Android 13 and 14. Jerry7994111 said they couldn't install it on their Samsung 21 Ultra with Android 14. So, they ended up ditching it and went straight for the latest [Spotify Premium Mod Apk](https://www.spotifypremiumapk.net/) from spotifypremiumapk.net. Can't blame them for wanting to enjoy their music without any headaches, right?

**Comment by skal3mar** [comment]
I have neglected the project a bit, but within a few days I intend to update the application and provide a version that will be compatible with Android 14.
